test_suites:
- name: cypress
  script_path: /root/okta/okta-help/ci-scripts
  script_name: cypress
  sort_order: '1'
  timeout: '15'
  criteria: MERGE
  queue_name: small
  script_env:
    SHALLOW_CLONE: true
    SKIP_CACHE_SETUP: true
