describe('End User landing page (en-US)', () => {
  beforeEach(() => {
    cy.visit('eu/en-us/Content/Topics/end-user/end-user-home.htm')
  })
  it('displays expected content structures in English', () => {
    cy.hasOktaHOCBanner('Okta Support')
    cy.hasCopyright()
    cy.hasLeftSideNav()
    cy.hasTOC(7)
    cy.hasBreadcrumbs('Documentation for end users')
    cy.hasPreviousTopicArrow()
    cy.hasNextTopicArrow()
    cy.hasTopMenuBar(4, 6)
    cy.hasBodyContent() 
    cy.hasTiles(4)
    cy.hasDeferAttrsCorrectlyApplied()
    cy.hasQualtrics()
    cy.hasMadCapSearchBar()
  })
})

describe('End User landing page (ja-JP)', () => {
  beforeEach(() => {
    cy.visit('eu/ja-jp/Content/Topics/end-user/end-user-home.htm')
  })
  it('displays expected content structures in Japanese', () => {
    cy.hasOktaHOCBanner('Okta Support')
    cy.hasCopyright()
    cy.hasLeftSideNav()
    cy.hasTOC(7)
    cy.hasBreadcrumbs('エンドユーザー向けのドキュメント')
    cy.hasPreviousTopicArrow()
    cy.hasNextTopicArrow()
    cy.hasTopMenuBar(4, 6)
    cy.hasBodyContent() 
    cy.hasTiles(4)
    cy.hasDeferAttrsCorrectlyApplied()
    cy.hasQualtrics()
    // cy.hasCoveoSearchBar()
  })
})